-- Ejecuta este SQL en Supabase > SQL Editor antes de activar USE_SUPABASE=true.

create table if not exists public.productos (
    id bigint generated by default as identity primary key,
    codigo text not null unique,
    nombre text not null,
    cantidad integer not null check (cantidad >= 0),
    valor numeric(12, 2) not null check (valor > 0),
    created_at timestamp with time zone default now()
);
